stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lg:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.picocloud.me
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
